### ISSUE TITLE
Problem on Executing mayapip examples

### ISSUE THREAD

**Issue by wamapi89** [robertjoosten/maya-pip#1]
Hello, thank you for providing the tool for importing python libraries to mayapy, which I need to do to execute your other tool (video2mocap) 
I manage to install the mayapip into my [machine](https://drive.google.com/file/d/1f29PM2BSouslTjbauKXdQkoDv1Rx637k/view?usp=sharing), but when i try to use the command:
mayapip install pyyaml --maya_version=2018 using the administration permission

- it produces this [erro](https://drive.google.com/file/d/13S64nmiE-cZK4mE-a0str5OTFzc2K-bG/view?usp=sharing)r: 

When i try to run it without administration permission

- it produces this [error](https://drive.google.com/file/d/1vJ6zvACYHF7vJSXeYg5M_UVpw-W2YIEM/view?usp=sharing).

I screenshot the errors, please have a look at the attached images in the hyperlinks.

Thank you very much!

**Comment by robertjoosten** [comment]
Hello,

As this tool is a wrapper on the existing pip functionality it is important you have the existing pip installed.
You can find how to do so here https://pip.pypa.io/en/stable/installing/
